apiVersion: v1
kind: Secret
metadata:
  name: grow-diary-secret
type: Opaque
stringData:
  DB_USER: "growth_diary_user"
  DB_PASSWORD: "GrowthDiary1234!"
  JWT_ACCESS_SECRET: "cloud_computing_2026_grow_access_secret_key"